name: kthcloud-ci

on:
  push:
    branches:
    - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }} # Define environment variable for the whole job

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.9.0' # Replace with your Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
     
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: registry.cloud.cbh.kth.se
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: registry.cloud.cbh.kth.se/your-image-name:${{ github.sha }}
        build-args:
          MONGODB_URI=${{ secrets.MONGODB_URI }} # Pass environment variable as build-arg